name: cycl3d

services:
  app:
    container_name: cycl3d-app
    build: .
    restart: unless-stopped
    ports:
      - 80:3000
    networks:
      - cycl3d_network
    env_file: "./server/.env.production"
    volumes:
      - cycl3d_volume:/app
    environment:
      - PGHOST=host.docker.internal
      - PGUSER=geoserver
      - PGDATABASE=advanced_gis
      - GEOSERVER_BASE=https://geoserver.seanbrooker.com/geoserver
      - BUN_INSTALL_CACHE_DIR=/bun/cache
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
      - "geoserver:172.18.0.2"

networks:
  cycl3d_network:
    external: true

volumes:
  cycl3d_volume:
    name: cycl3d_volume
